# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build, Test, and Package

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build and Test Environment
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nlp_env
          environment-file: dev_environment.yml
          python-version: 3.7
          auto-activate-base: false
      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          conda activate nlp_env && pytest --junitxml=results.xml --cov=nlprov --cov-report xml nlprov/test
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
      - name: Lint Tutorial Notebook
        shell: bash -l {0}